<?php

/**
 * @file
 * Contains content_planner.module.
 */

/**
 * Implements hook_theme().
 */
function content_planner_theme($existing, $type, $theme, $path) {

  return array(

    'content_planner_dashboard' => array(
      'variables' => array(
        'blocks' => array(),
      ),
    ),

    'content_planner_dashboard_block' => array(
      'variables' => array(
        'css_id' => NULL,
        'block_id' => NULL,
        'name' => array(),
        'block' => array(),
      ),
    ),

    'content_planner_dashboard_user_block' => array(
      'variables' => array(
        'users' => array(),
      ),
    ),

  );
}